server:
  port: 8081

spring:
  profiles:
    active: test
  datasource:
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

emt:
  enable: true  # 实际加不加都行，启动类上加了 @EnableEmt 就行，因为 EmtProperties 默认给的 true
  mode: create
#  auto-drop-column: true  # 配合 update 模式，删除无用列
  record-sql:
    enable: true
    record-type: file # 默认生成 .sql 文件
    folder-path: sql-log\ # 本项目下
    version: 1.0

